# Services definition for a Kontalk server
# DO NOT RUN docker-compose on this file directly
# Use ./launcher start

version: '2'

services:
  db:
    container_name: "${INSTANCE_NAME}_db"
    image: mysql:5.6
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: on-failure
    environment:
      - MYSQL_DATABASE=kontalk
      - MYSQL_USER=kontalk
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    networks:
      - default

  xmpp:
    container_name: "${INSTANCE_NAME}_xmpp"
    depends_on:
      - db
    image: kontalk/xmppserver:${IMAGE_VERSION}
    ports:
      - "${XMPP_LISTEN_PORT}:5222"
      - "${XMPPS_LISTEN_PORT}:5223"
      - "${XMPPS2S_LISTEN_PORT}:5269"
    volumes:
      - xmpp_data:/home/kontalk/data
      - ./config:/tmp/data
    restart: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "100"
    environment:
      - MYSQL_DATABASE=kontalk
      - MYSQL_USER=kontalk
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_TIMEZONE
      - DATABASE_BASELINE
      - XMPP_SERVICE
      - XMPP_LISTEN_PORT
      - XMPPS_LISTEN_PORT
      - XMPPS2S_LISTEN_PORT
    networks:
      - default
      - elk

  httpupload:
    container_name: "${INSTANCE_NAME}_httpupload"
    image: kontalk/httpupload
    ports:
      - "${HTTPUPLOAD_LISTEN_PORT}:8828"
    volumes:
      - httpupload_data:/home/kontalk/disk
      - ./config/config.yml.in:/tmp/config.yml.in
    restart: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      - XMPP_SERVICE
      - HTTPUPLOAD_MAX_SIZE
      - HTTPUPLOAD_LISTEN_PORT
      - HTTPUPLOAD_PUT_URL
      - HTTPUPLOAD_GET_URL
    networks:
      - default
      - elk

volumes:
  db_data:
  xmpp_data:
  httpupload_data:

networks:
  default:
  elk:
# Uncomment to enable link to ELK logging
#    external:
#      name: "${INSTANCE_NAME}log_elk"
