# Services definition for a Kontalk server
# You may run this stack through `docker stack deploy -c docker-compose.yml <instance_name>`
# or use `./launcher start` if you want a more powerful tool

version: '3.3'

services:
  db:
    image: mysql:5.6
    volumes:
      - db_data:/var/lib/mysql
    configs:
      - source: ./mysql/my.cnf
        target: /etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=kontalk
      - MYSQL_USER=kontalk
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    networks:
      - default

  xmpp:
    image: kontalk/xmppserver:${IMAGE_VERSION}
    ports:
      - "${XMPP_LISTEN_PORT}:5222"
      - "${XMPPS_LISTEN_PORT}:5223"
      - "${XMPPS2S_LISTEN_PORT}:5269"
    volumes:
      - xmpp_data:/home/kontalk/data
    configs:
      - source: ./config
        target: /tmp/data
    logging:
      options:
        max-size: "10m"
        max-file: "100"
    environment:
      - MYSQL_DATABASE=kontalk
      - MYSQL_USER=kontalk
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_TIMEZONE
      - DATABASE_BASELINE
      - XMPP_SERVICE
      - XMPP_LISTEN_PORT
      - XMPPS_LISTEN_PORT
      - XMPPS2S_LISTEN_PORT
    networks:
      - default
      - elk

  httpupload:
    image: kontalk/httpupload
    ports:
      - "${HTTPUPLOAD_LISTEN_PORT}:8828"
    volumes:
      - httpupload_data:/home/kontalk/disk
    configs:
      - source: ./config/config.yml.in
        target: /tmp/config.yml.in
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      - XMPP_SERVICE
      - HTTPUPLOAD_MAX_SIZE
      - HTTPUPLOAD_LISTEN_PORT
      - HTTPUPLOAD_PUT_URL
      - HTTPUPLOAD_GET_URL
    networks:
      - default
      - elk

volumes:
  db_data:
  xmpp_data:
  httpupload_data:

networks:
  default:
  elk:
# Uncomment to enable link to ELK logging
#    external:
#      name: "${INSTANCE_NAME}log_elk"
